name: 📋 Engineering Standards Violation
description: Report a violation of engineering standards or code quality issues
title: "[Standards]: "
labels: ["engineering-standards", "code-quality"]
body:
  - type: markdown
    attributes:
      value: |
        Report violations of the project's engineering standards defined in AGENTS.md and the engineering-standards/ directory.

  - type: dropdown
    id: standard-category
    attributes:
      label: Standard Category
      description: Which category of standard is violated?
      options:
        - SOLID Principles
        - Code Quality (method/class length, parameters)
        - TDD/Testing Standards
        - Commit Message Format
        - Micro-Commit Workflow
        - Documentation Standards
        - Other
    validations:
      required: true

  - type: textarea
    id: standard-violated
    attributes:
      label: Standard Violated
      description: Which specific standard or rule is violated?
      placeholder: |
        Example: "Maximum method length of 15 lines exceeded"
        Example: "Class has more than 2 private methods (SRP violation)"
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the violation located?
      placeholder: |
        File: src/main/java/com/liftit/Example.java
        Class: ExampleClass
        Method: exampleMethod (lines 45-78)
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current code or practice that violates the standard
      placeholder: Describe what currently exists...
      render: java
    validations:
      required: true

  - type: textarea
    id: expected-state
    attributes:
      label: Expected State
      description: How should the code be refactored to comply with the standard?
      placeholder: Describe the compliant approach...
      render: java
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this violation?
      options:
        - Low - Minor deviation, cosmetic
        - Medium - Affects maintainability
        - High - Violates core principles, affects quality
        - Critical - Blocks production readiness
    validations:
      required: true

  - type: textarea
    id: refactoring-plan
    attributes:
      label: Proposed Refactoring Plan
      description: Steps to fix the violation (optional)
      placeholder: |
        1. Extract method X
        2. Apply Strategy pattern
        3. Update tests

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Add context here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have verified this violates the documented engineering standards
          required: true
        - label: I have checked if this is already tracked in another issue
          required: true
