--liquibase formatted sql

--changeset liftit:create-exercises-table
CREATE TABLE exercises (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)             NOT NULL,
    category_id BIGINT                   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by  BIGINT                   NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by  BIGINT                   NOT NULL,
    CONSTRAINT pk_exercises PRIMARY KEY (id),
    CONSTRAINT uq_exercises_name UNIQUE (name),
    CONSTRAINT fk_exercises_category   FOREIGN KEY (category_id) REFERENCES exercise_categories (id),
    CONSTRAINT fk_exercises_created_by FOREIGN KEY (created_by)  REFERENCES users (id),
    CONSTRAINT fk_exercises_updated_by FOREIGN KEY (updated_by)  REFERENCES users (id)
);
--rollback DROP TABLE exercises;

--changeset liftit:create-exercise-muscle-groups-table
CREATE TABLE exercise_muscle_groups (
    exercise_id BIGINT NOT NULL,
    muscle_id   BIGINT NOT NULL,
    CONSTRAINT pk_exercise_muscle_groups PRIMARY KEY (exercise_id, muscle_id),
    CONSTRAINT fk_emg_exercise FOREIGN KEY (exercise_id) REFERENCES exercises (id) ON DELETE CASCADE,
    CONSTRAINT fk_emg_muscle   FOREIGN KEY (muscle_id)   REFERENCES muscles (id)
);
--rollback DROP TABLE exercise_muscle_groups;

--changeset liftit:reserve-exercises-id-sequence
-- Reserve IDs 1-99 for system-defined exercises; real exercises start at 100
ALTER SEQUENCE exercises_id_seq RESTART WITH 100;
--rollback ALTER SEQUENCE exercises_id_seq RESTART WITH 1;
