--liquibase formatted sql

--changeset liftit:create-workouts-table
CREATE TABLE workouts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                   NOT NULL,
    status       VARCHAR(20)              NOT NULL,
    started_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    notes        VARCHAR(1000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by   BIGINT                   NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by   BIGINT                   NOT NULL,
    CONSTRAINT pk_workouts PRIMARY KEY (id),
    CONSTRAINT fk_workouts_user       FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_workouts_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_workouts_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);
--rollback DROP TABLE workouts;
