--liquibase formatted sql

--changeset liftit:create-workout-exercises-table
CREATE TABLE workout_exercises (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workout_id  BIGINT       NOT NULL,
    exercise_id BIGINT       NOT NULL,
    order_index INTEGER      NOT NULL,
    notes       VARCHAR(500),
    CONSTRAINT pk_workout_exercises          PRIMARY KEY (id),
    CONSTRAINT fk_workout_exercises_workout  FOREIGN KEY (workout_id)  REFERENCES workouts   (id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_exercises_exercise FOREIGN KEY (exercise_id) REFERENCES exercises  (id)
);
--rollback DROP TABLE workout_exercises;
