--liquibase formatted sql

--changeset liftit:create-workout-sets-table
CREATE TABLE workout_sets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workout_exercise_id BIGINT         NOT NULL,
    set_number          INTEGER        NOT NULL,
    reps                INTEGER        NOT NULL,
    weight_value        NUMERIC(10, 4) NOT NULL,
    weight_unit         VARCHAR(10)    NOT NULL,
    rpe                 INTEGER,
    CONSTRAINT pk_workout_sets               PRIMARY KEY (id),
    CONSTRAINT fk_workout_sets_we            FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercises (id) ON DELETE CASCADE
);
--rollback DROP TABLE workout_sets;
