--liquibase formatted sql

--changeset liftit:fix-users-table
-- Remove stale columns from the pre-Auth0 design
ALTER TABLE users DROP CONSTRAINT uq_users_username;
ALTER TABLE users DROP COLUMN username;
ALTER TABLE users DROP COLUMN password;

-- Replace UUID primary key with BIGINT identity
ALTER TABLE users DROP CONSTRAINT pk_users;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Add auth0_id (the Auth0 sub claim — stable identifier, never changes)
ALTER TABLE users ADD COLUMN auth0_id VARCHAR NOT NULL DEFAULT '';
ALTER TABLE users ADD CONSTRAINT uq_users_auth0_id UNIQUE (auth0_id);
ALTER TABLE users ALTER COLUMN auth0_id DROP DEFAULT;

-- Fix created_at to include time zone
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
ALTER TABLE users ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;

-- Add missing audit columns
ALTER TABLE users ADD COLUMN created_by BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE users ADD COLUMN updated_by BIGINT NOT NULL DEFAULT 0;

-- Seed the system admin user (id=1); IDs 1-99 are reserved for system accounts
-- created_by and updated_by self-reference id=1 (system admin owns itself)
INSERT INTO users (id, auth0_id, email, created_at, created_by, updated_at, updated_by)
OVERRIDING SYSTEM VALUE
VALUES (1, 'system', 'system@liftit.internal', now(), 1, now(), 1);

-- Now that the seed row exists, add FK constraints for audit columns
ALTER TABLE users ADD CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE users ADD CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id);

-- Remove the temporary DEFAULT 0 used to satisfy NOT NULL during column addition
ALTER TABLE users ALTER COLUMN created_by DROP DEFAULT;
ALTER TABLE users ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE users ALTER COLUMN updated_by DROP DEFAULT;

-- Reserve IDs 1-99 for system accounts; real users start at 100
ALTER SEQUENCE users_id_seq RESTART WITH 100;
--rollback ALTER SEQUENCE users_id_seq RESTART WITH 1;
--rollback ALTER TABLE users DROP CONSTRAINT fk_users_updated_by;
--rollback ALTER TABLE users DROP CONSTRAINT fk_users_created_by;
--rollback DELETE FROM users WHERE id = 1;
--rollback ALTER TABLE users DROP COLUMN updated_by;
--rollback ALTER TABLE users DROP COLUMN updated_at;
--rollback ALTER TABLE users DROP COLUMN created_by;
--rollback ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC';
--rollback ALTER TABLE users DROP CONSTRAINT uq_users_auth0_id;
--rollback ALTER TABLE users DROP COLUMN auth0_id;
--rollback ALTER TABLE users DROP CONSTRAINT pk_users;
--rollback ALTER TABLE users DROP COLUMN id;
--rollback ALTER TABLE users ADD COLUMN id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;
--rollback ALTER TABLE users ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';
--rollback ALTER TABLE users ADD COLUMN username VARCHAR(20) NOT NULL DEFAULT '';
--rollback ALTER TABLE users ADD CONSTRAINT uq_users_username UNIQUE (username);
