--liquibase formatted sql

--changeset liftit:create-user-profiles-table
CREATE TABLE user_profiles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT                   NOT NULL,
    username         VARCHAR(30)              NOT NULL,
    display_name     VARCHAR(100),
    gender           VARCHAR(20),
    birthdate        DATE,
    height_cm        DECIMAL(5, 1),
    units_preference VARCHAR(10)              NOT NULL DEFAULT 'metric',
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       BIGINT                   NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by       BIGINT                   NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id),
    CONSTRAINT uq_user_profiles_user_id UNIQUE (user_id),
    CONSTRAINT uq_user_profiles_username UNIQUE (username),
    CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_profiles_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_user_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
    CONSTRAINT chk_user_profiles_units_preference CHECK (units_preference IN ('metric', 'imperial'))
);
--rollback DROP TABLE user_profiles;
